### ISSUE TITLE
don't create the same variable

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#11]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_2/index.js#L25
не создавай повторно переменную с таким же именем, всё равно что они в разной области видимости, в дальнейшем можно запутаться

**Comment by ElectricalVeins** [comment]
а как назвать объект, который создаёт функция createOverlay ?

**Comment by StereoZP** [comment]
overlayObject

**Comment by ElectricalVeins** [comment]
а нет смысла дублировать тип переменной в её названии

**Comment by StereoZP** [comment]
тогда в функции назови по другому, для того чтобы было разночтение

**Comment by ElectricalVeins** [comment]
так наоборот, функция идеально отображает то, что она делает
а переменная идеально отображает то, что в ней лежит

**Comment by ElectricalVeins** [comment]
Как вариант, можем вынести эту функцию в отдельный файлик, что бы не смущать видимым обилием "оверлеев"

**Comment by StereoZP** [comment]
Хорошее решение
