### ISSUE TITLE
what div?

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#12]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_2/index.js#L29
назови переменную нормально

**Comment by ElectricalVeins** [comment]
например sideMenuDiv?

**Comment by StereoZP** [comment]
Так, чтоб тебе понятно было за что отвечает данная переменная

**Comment by ElectricalVeins** [comment]
так мне и так понятно

**Comment by StereoZP** [comment]
а тому кто будет после тебя взаимодействовать с твоим кодом будет не понятно
