### ISSUE TITLE
лучше использовать element.addEventListener()

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#3]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_1/index.js#L10

**Comment by ElectricalVeins** [comment]
А какая разница, если и так работает?

**Comment by StereoZP** [comment]
разница в расширяемости, на онклик только одну функцию повесить можно

**Comment by ElectricalVeins** [comment]
Так я только одну функцию и вешаю сейчас

**Comment by StereoZP** [comment]
Привыкнешь и всегда будешь так писать

**Comment by StereoZP** [comment]
А откуда ты знаешь, что не нужно будет? Сегодня требование такие, завтра другие.
