### ISSUE TITLE
зачем написано через else if?

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#4]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_1/index.js#L13

**Comment by ElectricalVeins** [comment]
Потому что если остаток 0, то нужно сделать одно, а если остаток 1, то нужно делать другое

**Comment by StereoZP** [comment]
так напиши через ещё один if

**Comment by ElectricalVeins** [comment]
так а какая разница, так у меня остаётся синтаксически одна единая конструкция - читабельнее

**Comment by StereoZP** [comment]
В твоём случае if выполняется в зависимости от условий, а в моём случае случае они выполняются безусловно, то есть не зависит от выполнения предыдущих if предложений.

**Comment by StereoZP** [comment]
Нет смысла во второй проверке, так как у тебя только два ключа в info лежит, при делении на 2 остаток либо 0, либо 1. Поэтому if можно написать на один кейс.
