### ISSUE TITLE
Нужно вызывать в head

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#8]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_2/index.html#L41

**Comment by StereoZP** [comment]
Из-за того что стили применил в голове, не заметил что вызываешь скрипт в голове, вот тебе и проблема

**Comment by ElectricalVeins** [comment]
размещать тег script в head это из хороших практик. потому что это не контент

**Comment by StereoZP** [comment]
Проблем нет, я из-за стилей не заметил что скрипт вызывается в голове а не в теле страницы, поэтому всё гуд, можно закрывать ишью.
