### ISSUE TITLE
incorrect name of variable

### ISSUE THREAD

**Issue by StereoZP** [ElectricalVeins/bad-code-example#9]
https://github.com/ElectricalVeins/bad-code-example/blob/c1bff580556f0f498bf4f5b10e5c687cd3c6fe1b/review_2/index.js#L8
мне не понятно за что отвечает div, назови так, чтоб было понятно за что отвечает эта переменная

**Comment by ElectricalVeins** [comment]
sideMenuDiv?

**Comment by StereoZP** [comment]
Можно и так
